//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.0
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLK.AspNet.Identity {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CLK.AspNet.Identity.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Name {0} is already taken. 的當地語系化字串。
        /// </summary>
        internal static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission already in role. 的當地語系化字串。
        /// </summary>
        internal static string PermissionAlreadyInRole {
            get {
                return ResourceManager.GetString("PermissionAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PermissionId not found. 的當地語系化字串。
        /// </summary>
        internal static string PermissionIdNotFound {
            get {
                return ResourceManager.GetString("PermissionIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is not in role. 的當地語系化字串。
        /// </summary>
        internal static string PermissionNotInRole {
            get {
                return ResourceManager.GetString("PermissionNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} cannot be null or empty. 的當地語系化字串。
        /// </summary>
        internal static string PropertyTooShort {
            get {
                return ResourceManager.GetString("PropertyTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Store does not implement IPermissionRoleStore&lt;TPermission&gt;. 的當地語系化字串。
        /// </summary>
        internal static string StoreNotIPermissionRoleStore {
            get {
                return ResourceManager.GetString("StoreNotIPermissionRoleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Store does not implement IQueryablePermissionStore&lt;TPermission&gt;. 的當地語系化字串。
        /// </summary>
        internal static string StoreNotIQueryablePermissionStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryablePermissionStore", resourceCulture);
            }
        }
    }
}
